### ISSUE TITLE
LedMatrix GFX Demos?

### ISSUE THREAD

**Issue by pl4hh** [frumperino/FrekvensPanel#4]
No issue, but i was wondering if you tried to get some gfx demos running:
https://github.com/marcmerlin/FastLED_NeoMatrix_SmartMatrix_LEDMatrix_GFX_Demos

I'm fairly new into LEDs and i'm not sure about all those different libs for different LED/Matrix. So maybe already tried to get them running, or if i should stop right here because it's technically different LED interface?

**Comment by frumperino** [comment]
At the moment I'm only supporting the Adafruit GFX library with this project, sorry.
