### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by prashnts** [frumperino/FrekvensPanel#8]
Hi!
Thanks for this great library! I used it recently in my repo to use it as esphome display component.

Can you specify which license the code is made available under?

**Comment by frumperino** [comment]
Hi. Sorry for the late response. I don't know how to formally add a license. Just treat it as public domain, I don't have time to maintain this and the product was discontinued from IKEA / TE. Very glad to know you got some use out of it. Please feel free to use the code however you see fit.

**Comment by prashnts** [comment]
Great, I'll use a public domain license for my code as well.

It's a shame they discontinued it, but I'm glad I grabbed three of them while I still had time! Although its not a surprise since their implementation was quite disappointing.

Thanks for this library again! I'll try to explore the undocumented features later.

It's at https://github.com/prashnts/esphome-frekvens-panel
